Bistooltip_classes = {}
Bistooltip_phases = {}

Bistooltip_classes_indexes = {
    ["druid"] = 1,
    ["Hunter"] = 2,
    ["Mage"] = 3,
    ["Paladin"] = 4,
    ["Priest"] = 5,
    ["Rogue"] = 6,
    ["shaman"] = 7,
    ["Warlock"] = 8,
    ["Warrior"] = 9
}

Bistooltip_spec_icons = {};
Bistooltip_spec_icons["druid"] = {};
Bistooltip_spec_icons["druid"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\DRUID.blp";
Bistooltip_spec_icons["druid"]["balance"] = "Interface/Icons/Spell_nature_starfall.blp";
Bistooltip_spec_icons["druid"]["feral-tank"] = "Interface/Icons/Ability_racial_bearform.blp";
Bistooltip_spec_icons["druid"]["feral-dps"] = "Interface/Icons/Ability_druid_catform.blp";
Bistooltip_spec_icons["druid"]["restoration"] = "Interface/Icons/Spell_nature_healingtouch.blp";
Bistooltip_spec_icons["Hunter"] = {};
Bistooltip_spec_icons["Hunter"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\HUNTER.blp";
Bistooltip_spec_icons["Hunter"]["Beast mastery"] = "Interface/Icons/Ability_hunter_beasttaming.blp";
Bistooltip_spec_icons["Hunter"]["Marksmanship"] = "Interface/Icons/Ability_marksmanship.blp";
Bistooltip_spec_icons["Hunter"]["Survival"] = "Interface/Icons/Ability_hunter_swiftstrike.blp";
Bistooltip_spec_icons["Mage"] = {};
Bistooltip_spec_icons["Mage"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\MAGE.blp";
Bistooltip_spec_icons["Mage"]["Arcane"] = "Interface/Icons/Spell_holy_magicalsentry.blp";
Bistooltip_spec_icons["Mage"]["Fire"] = "Interface/Icons/Spell_Fire_FireBolt02.blp";
Bistooltip_spec_icons["Mage"]["Fire FFB"] = "Interface/Icons/Ability_mage_frostfirebolt.blp";
Bistooltip_spec_icons["Mage"]["Frost"] = "Interface/Icons/Spell_Frost_FrostBolt02.blp";
Bistooltip_spec_icons["Paladin"] = {};
Bistooltip_spec_icons["Paladin"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\PALADIN.blp";
Bistooltip_spec_icons["Paladin"]["Holy"] = "Interface/Icons/Spell_holy_holybolt.blp";
Bistooltip_spec_icons["Paladin"]["Protection"] = "Interface/Icons/Spell_holy_devotionaura.blp";
Bistooltip_spec_icons["Paladin"]["Retribution"] = "Interface/Icons/Spell_Holy_AuraOfLight.blp";
Bistooltip_spec_icons["Priest"] = {};
Bistooltip_spec_icons["Priest"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\PRIEST.blp";
Bistooltip_spec_icons["Priest"]["Discipline"] = "Interface/Icons/Spell_holy_wordfortitude.blp";
Bistooltip_spec_icons["Priest"]["Holy"] = "Interface/Icons/Spell_holy_holybolt.blp";
Bistooltip_spec_icons["Priest"]["Shadow"] = "Interface/Icons/Spell_shadow_shadowwordpain.blp";
Bistooltip_spec_icons["Rogue"] = {};
Bistooltip_spec_icons["Rogue"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\ROGUE.blp";
Bistooltip_spec_icons["Rogue"]["Assassination"] = "Interface/Icons/Ability_Rogue_Eviscerate.blp";
Bistooltip_spec_icons["Rogue"]["Combat"] = "Interface/Icons/Ability_backstab.blp";
Bistooltip_spec_icons["Rogue"]["Subtlety"] = "Interface/Icons/ability_stealth.blp";
Bistooltip_spec_icons["shaman"] = {};
Bistooltip_spec_icons["shaman"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\SHAMAN.blp";
Bistooltip_spec_icons["shaman"]["elemental"] = "Interface/Icons/Spell_Nature_Lightning.blp";
Bistooltip_spec_icons["shaman"]["enhancement"] = "Interface/Icons/Spell_Nature_LightningShield.blp";
Bistooltip_spec_icons["shaman"]["restoration"] = "Interface/Icons/Spell_Nature_HealingWaveLesser.blp";
Bistooltip_spec_icons["Warlock"] = {};
Bistooltip_spec_icons["Warlock"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\WARLOCK.blp";
Bistooltip_spec_icons["Warlock"]["Affliction"] = "Interface/Icons/Spell_Shadow_DeathCoil.blp";
Bistooltip_spec_icons["Warlock"]["Demonology"] = "Interface/Icons/Spell_Shadow_Metamorphosis.blp";
Bistooltip_spec_icons["Warlock"]["Destruction"] = "Interface/Icons/Spell_Shadow_RainOfFire.blp";
Bistooltip_spec_icons["Warlock"]["Destruction fire"] = "Interface/Icons/Spell_Shadow_RainOfFire.blp";
Bistooltip_spec_icons["Warrior"] = {};
Bistooltip_spec_icons["Warrior"]["classIcon"] = "Interface\\AddOns\\Bistooltip\\ClassWidget\\WARRIOR.blp";
Bistooltip_spec_icons["Warrior"]["Arms"] = "Interface/Icons/Ability_Rogue_Eviscerate.blp";
Bistooltip_spec_icons["Warrior"]["Fury"] = "Interface/Icons/Ability_Warrior_InnerRage.blp";
Bistooltip_spec_icons["Warrior"]["Protection"] = "Interface/Icons/Ability_Warrior_DefensiveStance.blp";